---
tags: You Dont Know JS (this와 객체 프로토타입, 비동기와 성능)
---

# Week 14

## Ch3. 프라미스

### 3.5 에러처리

- 프라미스 버림이 어떻게 합리적인 에러 처리를 할 수 있게 해주는지 상세한 부분을 살펴보자
- try catch는 동기적으로만 사용 가능하므로 비동기 코드 패턴에서는 무용지물이다.

```javascript
function foo() {
  setTimeout( function() {
    baz.bar()
  }, 1000)
}

try {
  foo();
} catch (err) {
  // 이거 실행 안됨
  console.error(err)
}
```
- 위 코드에서 error가 걸리지 않고 그냥 bar 함수가 undefined라고 나온다.
- try catch를 비동기로 사용하려면 어떻게든 실행 환경의 추가 지원이 꼭 필요한데, 이 문제는 4장 제너레이터에서 다룬다.


```javascript
function foo(cb) {
  setTimeout( function() {
    try {
      var x = baz.bar();
      cb(null, x);
    } catch (err) {
      cb(err)
    }
  }, 1000)
}

foo(function(err, val) {
  if (err) {
    console.error(err)
  } else {
    console.log(val)
  }
})
```

- 위 코드에서 foo 함수에 전달한 콜백은 첫 번째 인자 err를 통해 에러 신호를 감지할 것이다. err가 있으면 에러가 난거고 없으면 문제가 없었다는 뜻이다.
- 하지만 이런 형태는 여러 개를 조합하면 문제가 심각해진다. 수준이 제각각인 에러 우선 콜백이 if 문이 여기저기 널린 상태로 생긴다면 결국 콜백 지옥이나 다름 없다.

```javascript
var p = Promise.reject('허걱');

p.then(
  function fullfilled() {
    // 실행되지 않는다.
  },
  function rejected(err) {
    console.log(err) // 허걱
  }
)
```

- 위 코드는 정상적으로 에러를 잡지만 다른 경우를 보자

```javascript
var p = Promise.resolve(42);

p.then(
  function fulfilled(msg) {
    console.log(msg.toLowerCase())
  },
  function rejected(err) {
    // 실행되지 않는다.
  }
)
```

- msg에서 문법 오류가 발생했는데 왜 검지되지 않았을까. 이유는 이 에러 처리기의 소속은 프라미스 p고 이미 p는 이루어진 상태라서 그렇다. p는 불변값이기 때문에 에러 알림은 오직 p.then만이 반환한 프라미스만이 가능한데 여기서는 이 프라미스를 포착할 방법이 없다.
- 프라미스 API를 잘못 사용해서 프라미스 생성 과정에서 에러가 나면 그 결과는 바로 예외를 던진다. 

#### 3.4.1 절망의 구덩이
> 프로그래밍 언어는 대부분 개발자가 사고를 치면 '절망의 구덩이에 빠져 혹독한 대가를 치르는 방향으로 설계되어 있어서 제대로 실행하려면 정신을 바짝 차리고 열심히 코딩하여야 한다' 
> - 제프 앳우드

- 오히려 프로그램이 예상대로 처리되도록 '성공의 구덩이'를 기본적으로 파놓고 프로그램 실행을 실패하도록 만들어야 한다는 말이다.
- 프라미스 에러 처리는 분명히 '절망의 구덩이' 방식으로 설계되어 있다. 그래서 기본적으로 에러가 나도 프라미스 상태에 따라 무시할 수 있다고 보기 때문에 개발자가 깜빡 잊고 상태 감지를 하지 않으면 조용히 에러는 생을 마감한다.

- 사라진/ 버려진 프라미스의 에러를 잡으로면 반드시 프라미스 연쇄 끝부분에 catch를 써야 한다고 주장하는 개발자들이 있다.

```javascript
var p = Promise.resolve(42);

p.then(
  function fulfilled(msg) {
    console.log(msg.toLowerCase())
  },
  function rejected(err) {
    // 실행되지 않는다.
  }
).catch(handleErrors)
```

- 하지만 handleErrors에서 에러가 난다면? 이건 누가 잡을까. 그리고 또 catch가 반환한 프라미스는 누가 잡을까?

### 3.6 프라미스 패턴

#### 3.6.1 Promise.all([])

- 비동기 시퀀스는 주어진 시점에 단 한 개의 비동기 작업만 가능하다. 2개 이상의 단계가 동시에 움직이려면 어떻게 해야 할까?
- 복수의 병렬/동시 작업이 끝날 때까지 진행하지 않고 대기하는 관문이라는 장치가 있다. 이런 패턴을 구현한 것이 all 메서드이다.

```javascript
var p1 = request('http://some.url.1');
var p2 = request('http://some.url.2');

Promise.all([p1,p2])
.then(function(msgs) {
  // p1, p2가 둘 다 이루어져
  // 여기에 메시지가 전달된다.
  return request(
    'http://some.url.3/?v='+msgs.join(',')
  );
})
.then(function(msg) {
  console.log(msg)
})
```

- Promise.all([])은 보통 프라미스 인스턴스들이 담긴 배열 하나를 인자로 받고 호출 결과 반환된 프라미스는 이룸 메시지를 수신한다. 이 메시지는 배열에 나열한 순서대로 프라미스들을 통과하면서 얻어진 이룸 메시지의 배열이다.
- all에 전달하는 배열은 프라미스, 데너블, 즉시값 모두 가능하다. 배열값들은 하나씩 Promise.resolve를 통과하면서 진짜 프라미스임을 보장하고 즉시 값은 해당 값을 지닌 프라미스로 정규화된다.
- all이 반환한 메인 프라미스는 자신의 하위 프라미스들이 모두 이루어져야 이루어질 수 있다. 단 한 개의 프라미스라도 버려지면 Promise.all 프라미스 역시 곧바로 버려지며 다른 프라미스 결과도 덩달아 무효가 된다.

#### 3.6.2 Promise.race([])

- 결승선을 통과한 최초의 프라미스만 인정하는 패턴
- 걸쇠 패턴을 이용한 프라미스로, 배열을 인자로 받는다. all가 마찬가지로 프라미스, 데너블, 즉시값이 포함된 배열을 받을 수 있지만 즉시값은 이미 정해진 값이니 사실 인자로 넣는게 아무 의미가 없다.
- 하나라도 이루어진 프라미스가 있을 경우에 이루어지고 하나라도 버려지는 프라미스가 있어지면 버려진다.


```javascript
var p1 = request('http://some.url.1');
var p2 = request('http://some.url.2');

Promise.race([p1,p2])
.then(function(msg) {
  // p1, p2중 하나는 경합의 승자
  return request(
    'http://some.url.3/?v='+msg
  );
})
.then(function(msg) {
  console.log(msg)
})
```

- 프라미스 하나만 승자가 되기에 이룸값은 배열이 아닌 단일 메시지다.


#### 3.6.3 all([])/race([])의 변형

- all과 race를 변형한 패턴 중에 자주 쓰이는 것들이 있다.

1. none - all과 비슷하지만 이룸/버림이 정반대다. 모든 프라미스는 버려져야 하며, 버림이 이룸값이 되고 이룸이 버림값이 된다.
2. any - all과 유사하나 버림은 모두 무시하며, 하나만 이루어지면 된다.
3. first - any의 경합과 비슷하다. 최초로 프라미스가 이루어지고 난 이후엔 다른 이룸/버림은 간단히 무시한다.
4. last - first와 거의 같고 최후의 이룸 프라미스 하나만 승자가 된다는 것만 다르다.

#### 3.6.4 동시 순회

- 프라미스 리스트를 죽 순회하면서 각각에 대해 어떤 처리를 하고 싶은 경우가 있다. 처리 작업이 비동기적이거나 동시 실행될 수 있다면 많은 라이브러리에서 제공하는 비동기 버전의 유틸리티를 쓰면 된다.
- 코드는 분석을 못했습니다. 죄송합니다.